### ISSUE TITLE
All route related requests return me 400 error

### ISSUE THREAD

**Issue by v-glushkov** [perfahlen/AzureMapsRestServices#1]
Hi

Just as the title says - all route related requests give me 400 error. SearchAddressRequest as an example works fine. Happens to me with both versions - 1.0 and 2.0.

Thanks!

**Comment by perfahlen** [comment]
Can you provide with an example? I discovered that the Query parameter can be a  bit itchy.

**Comment by v-glushkov** [comment]
Well, so far I've only tried queries from your unit tests class:

```
var req = new RouteRequestDirections
			{
				Query = "52.50931,13.42936:52.50274,13.43872",
				VehicleEngineType = VehicleEngineType.Combustion
			};
			var directions = await _azureMapsServices.GetRouteDirections(req).ConfigureAwait(false);


			var req2 = new RouteRangeRequest
			{
				Query = "52.50931,13.42936",
				TimeBudgetInSec = "12000"

			};
			var range = await _azureMapsServices.GetRouteRange(req2).ConfigureAwait(false);

```
Error I get is "Response status code does not indicate success: 400 (Bad Request)."
Tried other geo coordinates taken from [ official documentation sample ](https://docs.microsoft.com/en-us/rest/api/maps/route) but still getting Bad request.

**Comment by perfahlen** [comment]
In short, the service returns: "When vehicleEngineType is combustion, fuelEnergyDensityInMJoulesPerLiter must be specified as well".

I have populated the actual return message from the service when error occurs. There is a new version on Nuget addressing this (2.0.2)

**Comment by v-glushkov** [comment]
Thanks a lot!

Now it makes sense, proper error messages are there and very helpful.
I've just removed VehicleEngineType property since I don't care much about precision of results at the moment and now it works fine!
