### ISSUE TITLE
Bug, SearchNearbyRequest class property CountrySet in is an int? and should be a string

### ISSUE THREAD

**Issue by StephaneBischoff** [perfahlen/AzureMapsRestServices#11]
Bug, SearchNearbyRequest class property CountrySet in is an int? and should be a string.

Other classes might have the same bug.

`public int? CountrySet { get; set; }`

**Comment by StephaneBischoff** [comment]
Created pull request https://github.com/perfahlen/AzureMapsRestServices/pull/12

**Comment by perfahlen** [comment]
Thank you!
