### ISSUE TITLE
GetSearchAddress not working with lat + lng with German locale

### ISSUE THREAD

**Issue by sibbl** [perfahlen/AzureMapsRestServices#13]
The following code

```
var am = new AzureMapsToolkit.AzureMapsServices("key");
var searchAddressRequest = new SearchAddressRequest
{
    Query = "test",
    Lat = 51.3,
    Lon = 12.3,
    Language = "de-DE"
};
var resp = await am.GetSearchAddress(searchAddressRequest);
```

always returns a Bad Request 400 and as one can see in Fiddler, the request includes `...&lat=51,3&lon=12,3&...`  (commas instead of points) on a machine set to German locale.

**Comment by perfahlen** [comment]
@sibbl , this should be fixed now. I am publishing a new nuget pkg (4.1.1)

Thank you for the report!
