### ISSUE TITLE
Azure Gov uses different host name

### ISSUE THREAD

**Issue by holtalanm** [perfahlen/AzureMapsRestServices#19]
Azure Maps Commercial uses the host name `atlas.microsoft.com`
Azure Maps for Government uses the host name `atlas.azure.us`

This library is currently impossible to use for Azure Maps for Government because the url is hard-coded into the methods.

**Comment by rbrundritt** [comment]
Would be good to have an optional parameter to pass in domain as there will like be others as gov clouds for other regions are supported.

**Comment by cmcclure-penlink** [comment]
I agree.

**Comment by perfahlen** [comment]
will prioritize this

**Comment by perfahlen** [comment]
what do you think about expanding the constructor to: 
```

public AzureMapsServices(string key, string baseDomain = "https://atlas.microsoft.com")

```
this will also give a hint how another domain should be passed in.

**Comment by cmcclure-penlink** [comment]
That totally what I wanted.

**Comment by perfahlen** [comment]
I pushed it, a new Nuget build is on the way. Test run seemed to be OK.

**Comment by cmcclure-penlink** [comment]
Updated the Nuget and tested it this morning on my project. Works like a charm. Thanks for the quick turnaround.
