### ISSUE TITLE
Handle multiple brandSet

### ISSUE THREAD

**Issue by csmac3144** [perfahlen/AzureMapsRestServices#20]
This works:

`            var sr = new SearchPoiRequest
            {
                Query= "brandSet=Homesense",
                Lat = 44.654239,
                Lon = -63.650956,
                Radius = 100000,
                Limit = 100
            };
`

and this works:

`            var sr = new SearchPoiRequest
            {
                Query= "brandSet=Marshalls",
                Lat = 44.654239,
                Lon = -63.650956,
                Radius = 100000,
                Limit = 100
            };
`

However, this does not:

`            var sr = new SearchPoiRequest
            {
                Query= "brandSet=Homesense,Marshalls",
                Lat = 44.654239,
                Lon = -63.650956,
                Radius = 100000,
                Limit = 100
            };
`

https://docs.microsoft.com/en-us/rest/api/maps/search/getsearchpoi

**Comment by csmac3144** [comment]
I added support for brandSet. Seems you have to set Query to "{}"
 in order for this to work.

**Comment by csmac3144** [comment]
The code example I gave is incorrect. brandSet does not go in query. It's a separate property.

**Comment by perfahlen** [comment]
Need to update the model, @csmac3144 thanks for finding this. Let's see if I get time, otherwise a PR is always welcome.

**Comment by perfahlen** [comment]
@csmac3144 this should be included in 5.0.2. New package today
