### ISSUE TITLE
SearchFuzzyReques.IdxSet doesn't correctly get applied to the query string

### ISSUE THREAD

**Issue by mtnvencenzo** [perfahlen/AzureMapsRestServices#22]
public string[] IdxSet { get; set; }

When using this the request fails as a BadRequest.

I think this is failing because of the .ToString() in the GetQuery() in BaseServices

**Comment by perfahlen** [comment]
thank you, just pushed a fix for a that, a new nuget pkg is its way

**Comment by mtnvencenzo** [comment]
Great thanks,  pulled down the latest package.  all is good!
