### ISSUE TITLE
DataSourcesGeometry JsonProperty name is invalid

### ISSUE THREAD

**Issue by sibbl** [perfahlen/AzureMapsRestServices#23]
I guess the comment shouldn't be used as the `JsonProperty` name here, right? :)

```
 [JsonProperty("Pass this as geometryId to the Get Search Polygon API to fetch geometry information for this result.")]
public string Id { get; set; }
```

Source: https://github.com/perfahlen/AzureMapsRestServices/blob/bc3ebfea5d6e5d6b684ae8fa24e816aeb0c47667/AzureMapsRestToolkit/AzureMapsRestToolkit/Search/DataSourcesGeometry.cs#L10

**Comment by perfahlen** [comment]
thank you, just pushed a fix for a that, a new nuget pkg is its way
