### ISSUE TITLE
Enums like Avoid do not translate into multiple Querystring entries

### ISSUE THREAD

**Issue by mothswiller** [perfahlen/AzureMapsRestServices#27]
This concerns certain querystring params such as Avoid

Avoid

Specifies something that the route calculation should try to avoid when determining the route. Can be specified multiple times in one request, for example, '&avoid=motorways&avoid=tollRoads&avoid=ferries'.

This cannot be achieved using the current model eg:

```c#
var req = new RouteRequestDirections
            {
                Query = sb.ToString(),                
                ComputeBestOrder = isOptimised,                
                RouteRepresentation = RouteRepresentation.polyline,
                //Avoid = Avoid.carpools | Avoid.tollRoads
               
            };
```
does not translate into a correct querystring parameter. The toolkit only allows one avoid property to be specified.

**Comment by perfahlen** [comment]
@mothswiller , Avoid is fixed. However other enums will need to change as well. Hopefully there will be a fix for other enums soon.

This library need a bit work to update the models and services.

**Comment by perfahlen** [comment]
@mothswiller , pushed and merged in master branch
