### ISSUE TITLE
Support EntityTypes parameter in SearchAddressReverseRequest

### ISSUE THREAD

**Issue by SaqibS** [perfahlen/AzureMapsRestServices#30]
The rest API corresponding to SearchAddressReverseRequest takes an EntityTypes parameter, which is not reflected in the SDK. It would be great to have this.

**Comment by perfahlen** [comment]
Thanks, I notice it a need for an update. Currently there's a dev bransch that is more accurate. Hope I can find some time soon to update this library and packages.

**Comment by SaqibS** [comment]
Just coming back to this and see there hasn't been a release in 9 months. I fully understand that this is a side project, and appreciate your open source contributions, but just wanted to check if the library is planned to be updatd any time soon?

**Comment by perfahlen** [comment]
@SaqibS yeah it is a side project. However since it has gained some popularity it needs to be maintained. Also Azure Maps having a   decent pace. However, there are some commits in dev branch that needs to be tested before releasing a new version.

**Comment by perfahlen** [comment]
@SaqibS fixed, is pushed in master, will be part of next release

**Comment by SaqibS** [comment]
Thanks very much.

Looking at 6.0.0, EntityTypes takes only a single value, despite the name being plural. Should it be a List? In the BingMapsRestToolkit this property does accept a list.

**Comment by perfahlen** [comment]
You can pass multiple values.
```
var req = new SearchAddressReverseRequest
{
    Query = "37.337,-121.89",
    EntityTypes = SearchAddressEntityTypes.Municipality | SearchAddressEntityTypes.PostalCodeArea
};
```

https://github.com/perfahlen/AzureMapsRestServices/blob/master/AzureMapsToolkit-Core-Test/UnitTest.cs#L325
