### ISSUE TITLE
SearchRequestBaseExtended.Offset should be sent as "ofs" in query string

### ISSUE THREAD

**Issue by humbleice** [perfahlen/AzureMapsRestServices#32]
I'm trying to use the `Offset` property for the `SearchAddressStructuredRequest`, but the query string param name being generated is "offset" when it should be "ofs".

This property already has a `JsonProperty` attribute for changing the name during serialization, but `BaseServices.GetQuery` doesn't use this attribute when creating query string params and looks for the `NameAttribute` instead.

**Comment by perfahlen** [comment]
fixed, is pushed in master. Will be in next release
