### ISSUE TITLE
Error when setting route directions instruction type

### ISSUE THREAD

**Issue by rbrundritt** [perfahlen/AzureMapsRestServices#7]
If you set the route request instruction type, an error is thrown "Object reference not set to an instance of an object.". Here is a simple example:

var routeResponse = await am.GetRouteDirections(new RouteRequestDirections()
{
    Query = "47.67491,-122.124:47.60323,-122.33028",
    InstructionsType = RouteInstructionsType.text
});

Here is the stack trace:

"   at AzureMapsToolkit.Common.BaseServices.GetQuery[T](T request, Boolean includeApiVersion, Boolean includeLanguage, Char firstChar)\r\n   at AzureMapsToolkit.Common.BaseServices.ExecuteRequest[T,U](String baseUrl, U req)\r\n   at AzureMapsToolkit.AzureMapsServices.GetRouteDirections(RouteRequestDirections routeReq)\r\n   at UwpRoutingSample.MainPage.CalculateRoute_Click(Object sender, RoutedEventArgs e)\r\n   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0(Object state)\r\n   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()"

**Comment by rbrundritt** [comment]
Made a pull request with a fix

**Comment by perfahlen** [comment]
Thank you
